# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    ls
    echo "Install"
    python3 -m pip install flake8 black isort
    echo "Run Black"
    black -l 100 .
    echo "Run isort"
    isort --profile black game.py
    echo "Run Flake8"
    flake8
  displayName: 'Code check'
